package com.czl.chatServer.bean;

import com.czl.chatClient.bean.Groupbean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CHANNEL_INFO".
 */
public class ChannelInfo implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 7578855298567382916L;
	private Long id;
    private String userId;
    private String channelid;
    private String channelname;
    private String channelremark;
    private String owner;
    private Integer membersum;
    private String logoid;
    private String logourl;
    private String channeltype;
    private Integer activiUsers;
    private String strOne;
    private String strTwo;
    private String strThree;
    private String strFour;
    private String strFive;
    public Groupbean toGroupbean(){
    	Groupbean bean=new Groupbean();
    	bean.setChannelNum(getMembersum());
    	bean.setGroupName(getChannelname());
    	bean.setLogourl(getLogourl());
    	bean.setGroupId(getChannelid());
    	return bean;
    }

    public ChannelInfo() {
    }

    public ChannelInfo(Long id) {
        this.id = id;
    }

    public ChannelInfo(Long id, String userId, String channelid, String channelname, String channelremark, String owner, Integer membersum, String logoid, String logourl, String channeltype, Integer activiUsers, String strOne, String strTwo, String strThree, String strFour, String strFive) {
        this.id = id;
        this.userId = userId;
        this.channelid = channelid;
        this.channelname = channelname;
        this.channelremark = channelremark;
        this.owner = owner;
        this.membersum = membersum;
        this.logoid = logoid;
        this.logourl = logourl;
        this.channeltype = channeltype;
        this.activiUsers = activiUsers;
        this.strOne = strOne;
        this.strTwo = strTwo;
        this.strThree = strThree;
        this.strFour = strFour;
        this.strFive = strFive;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getChannelid() {
        return channelid;
    }

    public void setChannelid(String channelid) {
        this.channelid = channelid;
    }

    public String getChannelname() {
        return channelname;
    }

    public void setChannelname(String channelname) {
        this.channelname = channelname;
    }

    public String getChannelremark() {
        return channelremark;
    }

    public void setChannelremark(String channelremark) {
        this.channelremark = channelremark;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public Integer getMembersum() {
        return membersum;
    }

    public void setMembersum(Integer membersum) {
        this.membersum = membersum;
    }

    public String getLogoid() {
        return logoid;
    }

    public void setLogoid(String logoid) {
        this.logoid = logoid;
    }

    public String getLogourl() {
        return logourl;
    }

    public void setLogourl(String logourl) {
        this.logourl = logourl;
    }

    public String getChanneltype() {
        return channeltype;
    }

    public void setChanneltype(String channeltype) {
        this.channeltype = channeltype;
    }

    public Integer getActiviUsers() {
        return activiUsers;
    }

    public void setActiviUsers(Integer activiUsers) {
        this.activiUsers = activiUsers;
    }

    public String getStrOne() {
        return strOne;
    }

    public void setStrOne(String strOne) {
        this.strOne = strOne;
    }

    public String getStrTwo() {
        return strTwo;
    }

    public void setStrTwo(String strTwo) {
        this.strTwo = strTwo;
    }

    public String getStrThree() {
        return strThree;
    }

    public void setStrThree(String strThree) {
        this.strThree = strThree;
    }

    public String getStrFour() {
        return strFour;
    }

    public void setStrFour(String strFour) {
        this.strFour = strFour;
    }

    public String getStrFive() {
        return strFive;
    }

    public void setStrFive(String strFive) {
        this.strFive = strFive;
    }

}
